//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Csharp_Group_Assignment.srvDatabase {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srvDatabase.IDatabase")]
    public interface IDatabase {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabase/checkUniqueCourse", ReplyAction="http://tempuri.org/IDatabase/checkUniqueCourseResponse")]
        bool checkUniqueCourse(string courseCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabase/checkUniqueCourse", ReplyAction="http://tempuri.org/IDatabase/checkUniqueCourseResponse")]
        System.Threading.Tasks.Task<bool> checkUniqueCourseAsync(string courseCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabase/checkUniqueProgram", ReplyAction="http://tempuri.org/IDatabase/checkUniqueProgramResponse")]
        bool checkUniqueProgram(string programName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabase/checkUniqueProgram", ReplyAction="http://tempuri.org/IDatabase/checkUniqueProgramResponse")]
        System.Threading.Tasks.Task<bool> checkUniqueProgramAsync(string programName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDatabaseChannel : Csharp_Group_Assignment.srvDatabase.IDatabase, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DatabaseClient : System.ServiceModel.ClientBase<Csharp_Group_Assignment.srvDatabase.IDatabase>, Csharp_Group_Assignment.srvDatabase.IDatabase {
        
        public DatabaseClient() {
        }
        
        public DatabaseClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DatabaseClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DatabaseClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DatabaseClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool checkUniqueCourse(string courseCode) {
            return base.Channel.checkUniqueCourse(courseCode);
        }
        
        public System.Threading.Tasks.Task<bool> checkUniqueCourseAsync(string courseCode) {
            return base.Channel.checkUniqueCourseAsync(courseCode);
        }
        
        public bool checkUniqueProgram(string programName) {
            return base.Channel.checkUniqueProgram(programName);
        }
        
        public System.Threading.Tasks.Task<bool> checkUniqueProgramAsync(string programName) {
            return base.Channel.checkUniqueProgramAsync(programName);
        }
    }
}
